/**
 * Global State to hold the active device reference once selected.
 * This prevents the user from having to select the printer for every single button click.
 */
let globalConnectedPrinter: any = null;
const COMMON_PRINTER_SERVICES = [
  'e7810a71-73ae-499d-8c15-faa9aef0c3f2', // Dothantech / Deli
  '000018f0-0000-1000-8000-00805f9b34fb', // Generic ESC/POS
  '49535343-fe7d-4ae5-8fa9-9fafd205e455', // ISDC / Serial
  '0000fee7-0000-1000-8000-00805f9b34fb'  // Generic
];

/**
 * Core Global Controller. Call this single function inside EVERY print button
 * event handler throughout the application.
 * 
 * @param {Uint8Array} rawEscPosBytes - The specific byte payload generated by the clicked button.
 */
export async function sendToGlobalThermalPrinter(rawEscPosBytes: Uint8Array): Promise<void> {
  try {
    // 1. If no printer is remembered, open the scanner modal on the current button click gesture
    if (!globalConnectedPrinter) {
      console.log("No printer active in state. Initializing device discovery...");
      const nav = navigator as any;
      globalConnectedPrinter = await nav.bluetooth.requestDevice({
        filters: [
          { namePrefix: 'S423' },
          { namePrefix: 'Deli' },
          { namePrefix: 'POS' }
        ],
        optionalServices: COMMON_PRINTER_SERVICES
      });
    }

    console.log(`Waking up printer from "Saved" state: ${globalConnectedPrinter.name}`);

    // 2. Open live RFCOMM/GATT pipe to execute the print job
    if (!globalConnectedPrinter.gatt) {
        throw new Error("GATT server not found on device.");
    }

    const server = await globalConnectedPrinter.gatt.connect();
    
    // Find a valid service and write characteristic
    let writePipe: any = null;
    const services = await server.getPrimaryServices();
    
    for (const service of services) {
      const characteristics = await service.getCharacteristics();
      for (const char of characteristics) {
        if (char.properties.write || char.properties.writeWithoutResponse) {
          writePipe = char;
          break;
        }
      }
      if (writePipe) break;
    }
    
    if (!writePipe) {
      throw new Error("No available write characteristic pipelines found.");
    }

    // 3. Stream the button's specific payload
    // Split into chunks to prevent MTU limits (max 512 bytes per chunk is safe for most BLE)
    const chunkSize = 512;
    for (let i = 0; i < rawEscPosBytes.length; i += chunkSize) {
      const chunk = rawEscPosBytes.slice(i, i + chunkSize);
      if (writePipe.properties.write) {
        await writePipe.writeValueWithResponse(chunk);
      } else {
        await writePipe.writeValueWithoutResponse(chunk);
      }
    }
    console.log("Print job completed successfully.");
    
    // 4. Disconnect instantly to free the hardware channel and return to "Saved" mode
    await globalConnectedPrinter.gatt.disconnect();

  } catch (error: any) {
    console.error("[CRITICAL] Global Printing Engine Failure:", error);
    // Reset state on failure so the next button click lets the user re-select the hardware
    globalConnectedPrinter = null; 
    alert(`Printing Failed: ${error.message}`);
  }
}

/**
 * Helper to wrap text according to the 32-character limit of the 58mm printer.
 */
export function wrapText(text: string, maxLength: number = 32): string[] {
    const lines: string[] = [];
    const words = text.split(' ');
    let currentLine = '';

    for (const word of words) {
        if ((currentLine + word).length > maxLength) {
            if (currentLine) {
                lines.push(currentLine.trim());
            }
            currentLine = word + ' ';
        } else {
            currentLine += word + ' ';
        }
    }
    if (currentLine) {
        lines.push(currentLine.trim());
    }
    return lines;
}

/**
 * Helper to pad a string to exactly a certain length (useful for aligning columns)
 */
export function padRight(text: string, length: number = 32): string {
    return text.padEnd(length, ' ').substring(0, length);
}

export function padLeft(text: string, length: number = 32): string {
    return text.padStart(length, ' ').substring(0, length);
}

/**
 * Format a key-value line where key is on the left, value is on the right, e.g. "Total:       Php 500.00"
 */
export function formatKeyValueLine(key: string, value: string, length: number = 32): string {
    if (key.length + value.length > length) {
        return key.substring(0, length - value.length - 1) + ' ' + value;
    }
    return key + value.padStart(length - key.length, ' ');
}

/**
 * Generates ESC/POS byte array for a thermal invoice and sends it to the printer
 */
export async function printBluetoothThermalInvoice(sale: any, template: any = {}) {
    const encoder = new TextEncoder();
    const payload: number[] = [];

    // Commands
    const INIT = [0x1B, 0x40];
    const ALIGN_CENTER = [0x1B, 0x61, 0x01];
    const ALIGN_LEFT = [0x1B, 0x61, 0x00];
    const BOLD_ON = [0x1B, 0x45, 0x01];
    const BOLD_OFF = [0x1B, 0x45, 0x00];
    const CUT = [0x1D, 0x56, 0x42, 0x00];

    payload.push(...INIT);

    // Header
    payload.push(...ALIGN_CENTER);
    payload.push(...BOLD_ON);
    const merchantName = template.merchant_name || 'Dr. Humba';
    for (const line of wrapText(merchantName.toUpperCase(), 32)) {
        payload.push(...encoder.encode(line + '\n'));
    }
    payload.push(...BOLD_OFF);

    if (template.merchant_address) {
        for (const line of wrapText(template.merchant_address, 32)) {
            payload.push(...encoder.encode(line + '\n'));
        }
    }
    if (template.merchant_contact) {
        payload.push(...encoder.encode(template.merchant_contact + '\n'));
    }
    if (template.merchant_tin) {
        payload.push(...encoder.encode(template.merchant_tin + '\n'));
    }

    payload.push(...encoder.encode('--------------------------------\n'));
    
    payload.push(...BOLD_ON);
    const headerText = template.header_text || 'SALES INVOICE';
    payload.push(...encoder.encode(headerText + '\n'));
    payload.push(...BOLD_OFF);

    payload.push(...encoder.encode('--------------------------------\n'));

    // Details
    payload.push(...ALIGN_LEFT);
    const dateStr = new Date(sale.created_at || new Date()).toLocaleString();
    payload.push(...encoder.encode(formatKeyValueLine('Date:', dateStr, 32) + '\n'));
    
    const invoiceNo = sale.control_number || String(sale.id).substring(0, 8);
    payload.push(...encoder.encode(formatKeyValueLine('Invoice No:', invoiceNo, 32) + '\n'));
    
    const branchName = sale.branch_name || 'Main Branch';
    payload.push(...encoder.encode(formatKeyValueLine('Branch:', branchName, 32) + '\n'));
    
    let cashierName = sale.cashier_email?.split('@')[0] || 'Staff';
    if (cashierName.length > 15) cashierName = cashierName.substring(0, 15);
    payload.push(...encoder.encode(formatKeyValueLine('Cashier:', cashierName, 32) + '\n'));
    
    const saleType = sale.sale_category || 'Dine in';
    payload.push(...encoder.encode(formatKeyValueLine('Sale Type:', saleType, 32) + '\n'));

    payload.push(...encoder.encode('--------------------------------\n'));

    // Items
    if (sale.items && Array.isArray(sale.items)) {
        for (const item of sale.items) {
            payload.push(...BOLD_ON);
            payload.push(...encoder.encode(item.item_name.toUpperCase() + '\n'));
            payload.push(...BOLD_OFF);
            const qtyStr = `  ${item.quantity} x P${Number(item.unit_price).toFixed(2)}`;
            const subtotalStr = `P${Number(item.subtotal).toFixed(2)}`;
            payload.push(...encoder.encode(formatKeyValueLine(qtyStr, subtotalStr, 32) + '\n'));
        }
    }

    payload.push(...encoder.encode('--------------------------------\n'));

    // Totals
    payload.push(...BOLD_ON);
    const totalStr = `P${Number(sale.total_amount).toFixed(2)}`;
    payload.push(...encoder.encode(formatKeyValueLine('TOTAL VALUE:', totalStr, 32) + '\n'));
    payload.push(...BOLD_OFF);

    payload.push(...encoder.encode('--------------------------------\n'));

    // Footer
    payload.push(...ALIGN_CENTER);
    const footerText = template.footer_text || 'Thank you for dining with us!\nCome back again!';
    const footerLines = footerText.split('\n');
    for (const line of footerLines) {
        for (const wrapped of wrapText(line, 32)) {
            payload.push(...encoder.encode(wrapped + '\n'));
        }
    }
    
    payload.push(...encoder.encode('\nDr. Humba\n\n\n'));

    // Cut
    payload.push(...CUT);

    await sendToGlobalThermalPrinter(new Uint8Array(payload));
}

/**
 * Generates ESC/POS byte array for a kitchen receipt and sends it to the printer
 */
export async function printBluetoothKitchenReceipt(sale: any) {
    const encoder = new TextEncoder();
    const payload: number[] = [];

    const INIT = [0x1B, 0x40];
    const ALIGN_CENTER = [0x1B, 0x61, 0x01];
    const ALIGN_LEFT = [0x1B, 0x61, 0x00];
    const BOLD_ON = [0x1B, 0x45, 0x01];
    const BOLD_OFF = [0x1B, 0x45, 0x00];
    const CUT = [0x1D, 0x56, 0x42, 0x00];

    payload.push(...INIT);
    payload.push(...ALIGN_CENTER);
    payload.push(...BOLD_ON);
    payload.push(...encoder.encode('*** KITCHEN ORDER ***\n\n'));
    payload.push(...BOLD_OFF);

    payload.push(...ALIGN_LEFT);
    const dateStr = new Date(sale.created_at || new Date()).toLocaleString();
    payload.push(...encoder.encode(`Date: ${dateStr}\n`));
    
    const invoiceNo = sale.control_number || String(sale.id).substring(0, 8);
    payload.push(...encoder.encode(`Order #: ${invoiceNo}\n`));
    
    const saleType = sale.sale_category || 'Dine in';
    payload.push(...encoder.encode(`Type: ${saleType}\n`));
    
    payload.push(...encoder.encode('--------------------------------\n'));

    payload.push(...BOLD_ON);
    if (sale.items && Array.isArray(sale.items)) {
        for (const item of sale.items) {
            const line = `${item.quantity} x ${item.item_name}`;
            for (const wrapped of wrapText(line, 32)) {
                payload.push(...encoder.encode(wrapped + '\n'));
            }
            if (item.notes) {
                payload.push(...BOLD_OFF);
                for (const wrapped of wrapText(`  Note: ${item.notes}`, 32)) {
                    payload.push(...encoder.encode(wrapped + '\n'));
                }
                payload.push(...BOLD_ON);
            }
        }
    }
    payload.push(...BOLD_OFF);

    payload.push(...encoder.encode('\n\n\n'));
    payload.push(...CUT);

    await sendToGlobalThermalPrinter(new Uint8Array(payload));
}

